services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: reviews_insights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/reviews_insights
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    command: uvicorn src.presentation.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

